services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  # --- UPDATED NER SERVICE TO BUILD LOCALLY ---
  ner-api:
    # Build and tag the local NER API image for Testcontainers compatibility
    build:
      context: .
      dockerfile: Dockerfile
    image: real-time-qou-system-ner-api:latest
    ports:
      - "8000:8000"

volumes:
  es_data:
    driver: local